# Generated by Django 3.0.4 on 2020-03-21 18:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('has_license', models.BooleanField(null=True)),
                ('user_type', models.CharField(choices=[('1', 'Landwirt'), ('2', 'Helfer')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('users', models.ManyToManyField(to='rest_server.User')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('needs_license', models.BooleanField()),
                ('description', models.TextField(max_length=1000)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.Job')),
                ('task_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_server.TaskType')),
                ('users', models.ManyToManyField(to='rest_server.User')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.TextField(max_length=1000)),
                ('location_type', models.CharField(choices=[('1', 'Bauernhof'), ('2', 'Feld')], max_length=1)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.Farm')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.User'),
        ),
        migrations.AddField(
            model_name='farm',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.User'),
        ),
    ]
