# Generated by Django 3.0.4 on 2020-03-21 21:31

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('has_license', models.BooleanField(null=True)),
                ('user_type', models.CharField(choices=[('1', 'Landwirt'), ('2', 'Helfer')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.Farm')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('needs_license', models.BooleanField()),
                ('description', models.TextField(max_length=1000)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.Job')),
                ('task_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_server.TaskType')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.TextField(max_length=1000)),
                ('location_type', models.CharField(choices=[('1', 'Bauernhof'), ('2', 'Feld')], max_length=1)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.Farm')),
            ],
        ),
    ]
