# Generated by Django 3.0.4 on 2020-03-21 16:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0002_auto_20200321_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
